"""Renders a validated StrategySpec as standalone backtesting.py Strategy source code.

Indicator math and per-rule condition evaluation happen upstream in tools/indicators.py,
which produces one boolean signal column per rule (see PrimitiveRule.signal_column in
tools/schemas.py) plus a raw ATR column and, for scalping, a session-filter column, in the
combined dataframe. This generator only has to AND the relevant boolean columns together
and apply the ATR-based SL/TP formula — keeping the emitted code simple and readable, per
the project's "simple, easy to translate to Python" requirement.

generate_code() always lints the spec first and refuses to render anything that fails —
code is never generated for a non-objective strategy, regardless of the caller.
"""

from tools.schemas import ATR_COLUMN, SESSION_COLUMN, StrategySpec
from tools.strategy_linter import lint


class UnlintedStrategyError(Exception):
    """Raised when asked to generate code for a spec that doesn't pass the linter."""


def generate_code(spec: StrategySpec, class_name: str = "GeneratedStrategy") -> str:
    result = lint(spec)
    if not result.passed:
        raise UnlintedStrategyError(
            f"refusing to generate code for a spec that fails the linter: {result.violations}"
        )

    signal_columns = [rule.signal_column for rule in spec.entry_rules]
    signal_columns += [rule.signal_column for rule in spec.confirmation_rules]

    conditions = [f"self.data.{col}[-1]" for col in signal_columns]
    if spec.session_filter is not None:
        conditions.append(f"self.data.{SESSION_COLUMN}[-1]")
    condition_expr = " and ".join(conditions)

    header = _render_header(spec, signal_columns)
    body = _render_class(class_name, condition_expr, spec.sl_formula.atr_multiple, spec.tp_formula.atr_multiple)
    return header + body


def _render_header(spec: StrategySpec, signal_columns: list[str]) -> str:
    session = spec.session_filter.value if spec.session_filter else "n/a"
    required_columns = f"{signal_columns!r}, plus a raw \"{ATR_COLUMN}\" column"
    if spec.session_filter is not None:
        required_columns += f", plus a \"{SESSION_COLUMN}\" column"
    return f'''"""Auto-generated by Strategy Creator. Do not edit by hand — regenerate instead.

Pair: {spec.inputs.pair.value}
Timeframe profile: {spec.inputs.timeframe_profile.value}
Risk level: {spec.inputs.risk_level.value}
Session: {session}

Expects the input dataframe to already contain the signal columns this strategy reads
(produced by tools/indicators.py): {required_columns}.
"""

from backtesting import Strategy


'''


def _render_class(class_name: str, condition_expr: str, sl_atr_multiple: float, tp_atr_multiple: float) -> str:
    return f'''class {class_name}(Strategy):
    sl_atr_multiple = {sl_atr_multiple}
    tp_atr_multiple = {tp_atr_multiple}

    def init(self):
        pass

    def next(self):
        if self.position:
            return
        atr = self.data.{ATR_COLUMN}[-1]
        if atr != atr:  # NaN guard: ATR not yet available during warm-up
            return
        if {condition_expr}:
            price = self.data.Close[-1]
            sl = price - self.sl_atr_multiple * atr
            tp = price + self.tp_atr_multiple * atr
            self.buy(sl=sl, tp=tp)
'''
